### ISSUE TITLE
Apropiación de generalidades JANO

### ISSUE THREAD

**Issue by a52290451** [udistrital/urano-funcionarios#10]
Realizar la apropiación de generalidades acerca del sistema JANO, contemplando su funcionamiento, roles y flujos de trabajo que realiza, así como las actividades necesarias por desarrollar en esta nueva fase, de acuerdo a los siguientes indicadores:

- [ ] Revisión e instalación de repositorios.
- [ ] Revisión de documentación.
- [ ] Análisis de requerimientos.

**criterio de aceptación**

- [ ] Registrar el estado actual en el que se recibe el sistema (Elaboración propia).
- [ ] Registrar inquietudes respecto a los requerimientos analizados.

**Links de apoyo**

1. Link pruebas: https://pruebasfuncionarios.portaloas.udistrital.edu.co/jano/
2. Repositorio: https://gitlab.com/unidistrital/funcionarios/-/tree/master/jano
3. Manuales: https://docs.google.com/spreadsheets/d/1q94p70_t46GpJ2eKVlBDFGRDWFxKCGMMclIWWCT-kjc/edit?usp=sharing
4. Usuario de prueba:
Id: cc52473666
Contraseña: sistemasoas

**Comment by Yaov05** [comment]
Por el momento se tiene acceso a 4 de los 5 documentos relacionados con los manuales de JANO, De los cuales se hace progresiva revisión para entender el funcionamiento del sistema.

- [x] Registro de Hoja de Vida (DVE).
- [x] Gestión de concursos activos (Concursantes).
- [x] INS Gestionar concurso (Administrador).
- [ ] INS Administración de jornadas electorales (ADMIN. OAS).
- [x] Administración de certificados electorales.
