### ISSUE TITLE
Arreglo de inicio de sesión.

### ISSUE THREAD

**Issue by a52290451** [udistrital/urano-funcionarios#11]
**Plan de estabilización de JANO**

- Se requiere dar solución a problema encontrado  en el  inicio de sesión el cual no muestra mensaje de error cuando se ingresan datos incorrectos.

**Criterios de aceptación**

- [x] Validación de solución del error en ambiente de pruebas.

**Comment by criss201x** [comment]
Se da solución al problema inyectando un script alert en el archivo [/blocks/registro/loginJano/funcion/formprocesor.php](https://gitlab.com/unidistrital/funcionarios/-/blob/master/agora/blocks/registro/loginAgora/funcion/formProcessor.php#L122) dando como resultado una notificación en el modulo de login en caso de que los credenciales de usuario o contraseña son incorrectos, despues de ejecutar el script, el aplicativo redirecciona nuevamente a la pantalla de login 
![Captura de pantalla de 2022-01-21 18-40-33](https://user-images.githubusercontent.com/57843585/150613814-a34d5642-44f1-4681-96c5-65ad8e38cd65.png)

**NOTA:** esta pendiente el commit en gitlab y su respectivo despliegue en ambiente de pruebas
