### ISSUE TITLE
Optimización - Módulo de gestión de usuarios

### ISSUE THREAD

**Issue by a52290451** [udistrital/urano-funcionarios#15]
Implementar las acciones necesarias para optimizar el módulo de gestión de usuarios en cuanto a tiempos de carga de información.

**Criterios de aceptación**

- [x] Commit con los cambios realizados.

**Comment by criss201x** [comment]
Se inyecta un script onload en el archivo [blocks/usuarios/gestionUsuarios/script/ready.php](https://gitlab.com/unidistrital/funcionarios/-/blob/master/agora/blocks/usuarios/gestionUsuarios/script/ready.php#L6) en el modulo de gestión de usuarios del aplicativo JANO dando como resultado una barra de carga previo a la carga de un componente de tipo datatable jquery
![Captura de pantalla de 2022-01-21 19-00-06](https://user-images.githubusercontent.com/57843585/150614916-3fdf2b04-014b-43d5-8e34-aa9b09b76259.png)

**Nota:** Este fix no optimiza en gran medida los tiempos de carga pero si el renderizado de la tabla usuarios en en front 
**Nota 2:** esta pendiente el commit de gitlab y su respectivo despliegue
