### ISSUE TITLE
Implementación - Módulo de Adutoría

### ISSUE THREAD

**Issue by a52290451** [udistrital/urano-funcionarios#16]
Se requiere implementar módulo de Auditoría en sistema JANO para el registro automatico de actividades.

**Criterios de aceptación**

- [x] Commit con los cambios realizados.
- [x] Pruebas funcionales.
- [x] Despliegue en ambiente de pruebas.
- [x] Despliegue en ambiente de producción.

**Comment by blackatze93** [comment]
![image](https://user-images.githubusercontent.com/6520535/153952091-450e8e8a-cf86-441d-9a43-86c02e9a1382.png)

Primer acercamiento a la implementación del módulo de gestión de auditoría, se muestran los menus y el formulario de consulta de los eventos.

**Comment by blackatze93** [comment]
![image](https://user-images.githubusercontent.com/6520535/158700224-5e349504-b78a-454e-98ed-76af40130519.png)

Implementación de los diferentes tipos de logs y filtros que tendrá el sistema de auditoría.

**Comment by blackatze93** [comment]
![image](https://user-images.githubusercontent.com/6520535/158700325-2f1f205e-38df-4bcf-a50f-ec1538813db2.png)

Filtros de acuerdo al tipo de registro generado en el sistema

**Comment by blackatze93** [comment]
![image](https://user-images.githubusercontent.com/6520535/158700610-1ca5928d-2ca2-41ec-8309-c9878252c2c4.png)

Listado de logs generados para el filtro seleccionado en la anterior pantalla

**Comment by blackatze93** [comment]
![image](https://user-images.githubusercontent.com/6520535/158700714-ad316e53-ecf4-4248-a5a0-f11c53d7446e.png)

Detallado del log seleccionado en la anterior pantalla del listado de logs

**Comment by blackatze93** [comment]
![image](https://user-images.githubusercontent.com/6520535/158700854-224337be-acba-4d25-aed7-06f0e31859cc.png)
Listado con errores generados en el sistema, está en pruebas para su revisión.

**Comment by blackatze93** [comment]
![image](https://user-images.githubusercontent.com/6520535/158700902-aa5477e6-1e7e-4f15-9c77-06796dec0909.png)
Detallado de un log de error de prueba.

**Comment by blackatze93** [comment]
[script_log_auditoria.txt](https://github.com/udistrital/urano-funcionarios/files/8274810/script_log_auditoria.txt)

Script con las consultas necesarias para la actualizacón de la BD

**Comment by blackatze93** [comment]
El repo temporal que contiene los cambios es el siguiente: https://github.com/blackatze93/jano

**Comment by a52290451** [comment]
Se deben realizar pruebas y documentar

Formato: https://docs.google.com/spreadsheets/d/1oymdKw9XVShKKk71AWzqUjPW-N26OdlRR_IB34X8Acs/edit#gid=481118634

**Comment by blackatze93** [comment]
![image](https://user-images.githubusercontent.com/6520535/164535086-781e9097-2209-4f39-996b-585c85fc3ded.png)

Ventana inicial Gestión Log errores

**Comment by blackatze93** [comment]
![image](https://user-images.githubusercontent.com/6520535/164535383-84020e80-3fcb-4596-bf39-749c36a7077f.png)

Ventana de detalle Gestión Log errores

**Comment by blackatze93** [comment]
![image](https://user-images.githubusercontent.com/6520535/164535572-75805574-3cbb-4837-81f3-40b2cb5ff091.png)

Ventana inicial Gestión Log transacciones

**Comment by blackatze93** [comment]
![image](https://user-images.githubusercontent.com/6520535/164535850-2e632f7b-583a-4164-b1ec-edf4106a19d2.png)

Ventana secundaria Gestión Log transacciones - Log de usuarios

**Comment by blackatze93** [comment]
![image](https://user-images.githubusercontent.com/6520535/164536275-827c8444-45bf-4076-b636-1547a3bc30e1.png)

Ventana consultar Auditoría usuario

**Comment by blackatze93** [comment]
Se hace implementación del modulo de auditoria en servidor de pruebas y de producción.
