### ISSUE TITLE
Cambiar nombre de repositorio.

### ISSUE THREAD

**Issue by juusechec** [udistrital/urano-funcionarios#2]
Se solicita cambiar nombre de repositorio de "Urano" a "urano-funcionarios".

https://github.com/udistrital/urano-funcionarios

De paso crear un repositorio que se llame "urano-estudiantes".

Gracias 😄

**Comment by miltonparra100** [comment]
Buen Día
Se cambió el nombre del repositorio Urano según solicitud.
Se creó el reporsitorio Udistrital/urano-estudiantes.
Gracias.
