### ISSUE TITLE
Revisión de modelo de proyecto curricular

### ISSUE THREAD

**Issue by mafeave** [udistrital/urano-funcionarios#3]
Se debe documentar el modelo de datos actual utilizado para la gestión de los proyectos curriculares en el SGA

**Comment by JuanPiedrahita** [comment]
Se crea documento de revisión de modelo de [proyecto curricular](https://docs.google.com/document/d/19VbK5XCEwW32tiZp7N7Kf6W_67r6nkrXvOshWG0bVJk/edit?usp=sharing).

**Comment by JuanPiedrahita** [comment]
Se agrega revisión de la [documentación](https://docs.google.com/document/d/1FpiWreNoBpbLMxiu62Nmm9wis7JmBLPfPz5FlknzQPc/edit?usp=sharing) de campus virtual para proyectos curriculares.

**Comment by JuanPiedrahita** [comment]
Se genera [imagen](https://drive.google.com/file/d/1cyFGdr9kY9yhTNa7VTxJP5yXX5bBvMax/view?usp=sharing) con modelo de tabla accra.

**Comment by JuanPiedrahita** [comment]
Se genera [modelo](https://drive.google.com/file/d/1SLgpUZMhkaO0OBB5XMw8CebcA5OI6hC3/view?usp=sharing) de proyecto curricular con tablas especificas de oracle.

**Comment by JuanPiedrahita** [comment]
Se revisa modelo avance con líder técnica y se dejan inquietudes para terminar la tarea.

**Comment by JuanPiedrahita** [comment]
SE recibe [modelo de admisiones](https://drive.google.com/open?id=1IOuxdqmJB1e4QjHUcGHvSgGpNbVV2P9a) y se empieza la revisión del mismo.

**Comment by JuanPiedrahita** [comment]
Se finaliza la revisión de los modelos entregados.

**Comment by mafeave** [comment]
Se verifica solución de dudas y documentación del modelo correspondiente.
