### ISSUE TITLE
Revisión modelo de datos de admisiones

### ISSUE THREAD

**Issue by mafeave** [udistrital/urano-funcionarios#4]
Se debe documentar el modelo de datos actual utilizado para la gestión de admisiones en el SGA

**Comment by JuanPiedrahita** [comment]
Se revisa modelo actual de admisiones de campus virtual, se genera modelo con pg modeler y se exporta a sql, dbm y png ([Carpeta con modelos](https://drive.google.com/drive/folders/1HTwNm8A0DndTUzZa0xqW6oRrMSNqluLu?usp=sharing)).

**Comment by JuanPiedrahita** [comment]
Se crea [documento](https://docs.google.com/document/d/17ZVDhTkD4r1mjYGqCSqOzWAjPLMztZqGjTBl-ro2prI/edit?usp=sharing) de revisión de modelo de admisiones.

**Comment by JuanPiedrahita** [comment]
Se espera usuario para consulta de modelo de admisiones en base de datos postgres, el usuario fue solicitado en el issue https://github.com/udistrital/urano-funcionarios/issues/5.

**Comment by JuanPiedrahita** [comment]
Definición de descripción de tablas del modelo de campus virtual en el documento.

**Comment by JuanPiedrahita** [comment]
Se revisa modelo avance con líder técnica y se solventan dudas del modelo,

**Comment by JuanPiedrahita** [comment]
Se termina la revisión del modelo sobre las tablas a las cual se tiene permiso.

**Comment by mafeave** [comment]
Se verifica la documentación del modelo, y la resolución de las dudas presentadas en el documento.
