### ISSUE TITLE
Creación de usuario de consulta a la base de datos de admisiones

### ISSUE THREAD

**Issue by mafeave** [udistrital/urano-funcionarios#5]
Se solicita la creación de un usuario de consulta sobre las siguientes tablas: 
- registro
- datos_basicos
- documentos
- posgrado_formacion
- posgrados_idiomas
- posgrados_descuentos
- pregrado_datos2
- admisiones_estrato
- admisiones_tipo_documento
- admisiones_discapacidad
- admisiones_estado_civil
- admisiones_salmin
- admisiones_estados
- pregrado_clasificacion
- admisiones_acrecbanasp
- pregrado_transferencia
- admisiones_reingreso

Base de datos: SARA_ADMISIONES
Host: 10.20.0.62, postgres

**Comment by fnrojash** [comment]
Buenos días

Ing. Mafe 

se crea el usuario en la instancia de postgres prueba local 10.20.0.62 en la bases de datos saraadmisiones:

Usuario: soportemfa
clave:  soportemfa2019

Ejecución:

[QUERY    ] CREATE USER "soportemfa" LOGIN NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1
[QUERY    ] alter role soportemfa WITH encrypted PASSWORD 'soportemfa2019'
[QUERY    ] GRANT consulta_saraadmisiones TO soportemfa
[QUERY    ] GRANT USAGE ON SCHEMA admisiones TO soportemfa
[QUERY    ] GRANT USAGE ON SCHEMA public TO soportemfa

Por favor validar, muchas gracias

**Comment by juusechec** [comment]
Tengan cuidado con compartir los issues públicamente y más si hay claves e ips que permitan a un atacante acceder a información privilegiada.

**Comment by mafeave** [comment]
@juusechec los proyectos están privados, solo usuarios asociados a la organización udistrital pueden verlos. Sin embargo si es necesario que la información de las conexiones se gestionen de forma más privada.

**Comment by mafeave** [comment]
Se prueba conexión pero se está presentando el siguiente error:
![image](https://user-images.githubusercontent.com/14035745/57717810-a41fa580-7641-11e9-887e-c14f71f446e1.png)

**Comment by fnrojash** [comment]
Buenos días

Ingeniera

Por favor regalarme la ip de su computador donde se va conectar para dar permisos de conexión para agregarlo en postgres (pg_hba.conf), sin este dato no podrás conectarte. 

Esta información debo enviarla al infraestructura por favor.

Muchas gracias

**Comment by jusech5** [comment]
@mafeave yo no pertenezco a la organización udistrital y puedo verlo todo y comentar sin necesidad de privilegios más allá de una cuenta de github.

**Comment by mafeave** [comment]
Se cierra dado que ya no es necesario consultar el modelo de admisiones.
